//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Lessons
    {
        public int ID_Lesson { get; set; }
        [Display(Name = "Teacher")]
        [Required]

        public Nullable<int> ID_Teacher { get; set; }
        [Required]
        [StringLength(80)]
        [Display(Name = "Lesson")]
        //[DataType(DataType.Custom)]
        public string Name_Lesson { get; set; }
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0 :yyy-MM-dd}")]
        [DataType(DataType.Date)]
        [Display(Name = "Date Lesson")]
        public Nullable<System.DateTime> Date_of_Lesson { get; set; }
    
        public virtual Teachers Teacher { get; set; }
    }
}
