//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class PDependedon
    {
        public PDependedon()
        {
            this.Points = new HashSet<Points>();
        }
    
        public int PDID { get; set; }
        [Required]
        [Display(Name = "Action")]
        [StringLength(30)]
        public string PDName { get; set; }
    
        public virtual ICollection<Points> Points { get; set; }
    }
}
