//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Points
    {
        public int PID { get; set; }
        [Required]
        [Display(Name = "Action")]
        public Nullable<int> PDID { get; set; }
        [Required]
        [Display(Name = "Student")]
        public Nullable<int> IDStudent { get; set; }
        [Required]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yyyy}")]
        [DataType(DataType.Date)]
        [Display(Name = "Date Score")]
        public Nullable<System.DateTime> Pdate { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber)]
        public Nullable<int> Score { get; set; }

        public virtual PDependedon PDependedon { get; set; }
        public virtual Students Student { get; set; }
    }
}
