//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Students
    {
        public Students()
        {
            this.Points = new HashSet<Points>();
        }
        public int ID_student { get; set; }
        [Required]
        [Display(Name = "Name student")]
        [StringLength(40)]
        [MaxLength(40)]
        [DataType(DataType.Text)]
        public string Name_student { get; set; }
        [Display(Name = "Phone ")]
        //[StringLength(11)]
        //[DataType(DataType.PhoneNumber)]
        //[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$",
        //           ErrorMessage = "Entered phone format is not valid.")]
        [RegularExpression(@"^(\d{11})$", ErrorMessage = "Wrong mobile")]
        public string TELL_Student { get; set; }
        [Display(Name = "Address")]
        [StringLength(100)]
        [Required]
        public string Addr_student { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = ("{0:yyyy-MM-dd}"))]
        [DataType(DataType.Date)]
        [Display(Name = "Date of birth")]
        public Nullable<System.DateTime> Date_of_birth { get; set; }
        [Required]
        [Display(Name = "Place")]
        public Nullable<int> ID_Place { get; set; }
        [Display(Name = "Image student")]
        public string img { get; set; }

        public virtual Places Place { get; set; }
        public virtual ICollection<Points> Points { get; set; }
    }
}
