//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace church
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Teachers
    {
        public Teachers()
        {
            this.Lessons = new HashSet<Lessons>();
        }
    
        public int ID_teacher { get; set; }
        [Required]
        [Display(Name = "Teacher")]
        [StringLength(50)]
        [MaxLength(50)]
        public string Name_teacher { get; set; }
        [RegularExpression(@"^(\d{11})$", ErrorMessage = "Wrong mobile")]
        [Display(Name = "Phone")]
        public string Tel_teacher { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        [DataType(DataType.Date)]
        [Display(Name = "Date Of berith teacher")]
        public Nullable<System.DateTime> Date_Of_berith { get; set; }
        [Required]
        [Display(Name = "Place")]
        public Nullable<int> ID_place { get; set; }
    
        public virtual ICollection<Lessons> Lessons { get; set; }
        public virtual Places Place { get; set; }
    }
}
